triggers:
  - type: meya.catchall
name: url_btn
states:
    
    text_buttons_state:
        component: meya.text_buttons
        properties:
            text: Your text here
            output: button_click
            buttons:
                - text: button_1
                  action: next
                - text: button_2
                  url: "https://docs.meya.ai/docs"
                - text: button_3
                  url: "https://chatbase.com/r?api_key={}&url=https://docs.meya.ai/docs&platform=myapp"
                - text: button_4
                  flow: "hello_world"
    next_state:
        component: meya.text
        properties:
            text: You clicked {{ flow.button_click }}